Polls improvements
UnigramDev/Unigram pull request #2133
Opened 2020-11-12 16:10 UTC by MarcAnt01

2020-11-13 09:03 UTC, FrayxRulez requested changes

2020-11-13 09:03 UTC, FrayxRulez commented on Unigram/Unigram/Controls/PollOptionControl.xaml.cs
> +using System;
Is `System` namespace really needed?

2020-11-13 09:03 UTC, FrayxRulez commented on Unigram/Unigram/Controls/PollOptionControl.xaml.cs
> +            else if (option.IsChosen && poll.Type is PollTypeQuiz && correct)
I would prefer to get rid of the else if, and to change the first if as following:
```
            if (option.IsChosen && poll.Type is PollTypeQuiz)
            {
                VisualStateManager.GoToState(LayoutRoot, correct ? "Correct" : "Wrong", false);
            }
```

2020-11-13 12:28 UTC, MarcAnt01 commented on Unigram/Unigram/Controls/PollOptionControl.xaml.cs
> +using System;
Yes
![image](https://user-images.githubusercontent.com/43090263/99072296-0bf6d980-25b4-11eb-9408-90933754fc27.png)

2020-11-13 13:23 UTC, MarcAnt01 commented on Unigram/Unigram/Controls/PollOptionControl.xaml.cs
> +            else if (option.IsChosen && poll.Type is PollTypeQuiz && correct)
Done

2020-11-14 09:02 UTC, FrayxRulez requested changes

2020-11-14 09:02 UTC, FrayxRulez commented on Unigram/Unigram/Themes/ThemeGreen.xaml
> +            <SolidColorBrush x:Key="MessagePollRightBrush" Color="{ThemeResource MessagePollRightColor}"/>
You're declaring `MessagePollCorrectColor` and using `MessagePollRightColor` after.

```suggestion
            <SolidColorBrush x:Key="MessagePollCorrectBrush" Color="{ThemeResource MessagePollCorrectColor}"/>
```

2020-11-14 09:02 UTC, FrayxRulez commented on Unigram/Unigram/Themes/ThemeGreen.xaml
> +            <SolidColorBrush x:Key="MessagePollRightBrush" Color="{ThemeResource MessagePollRightColor}"/>
You're declaring `MessagePollCorrectColor` and using `MessagePollRightColor` after.

```suggestion
            <SolidColorBrush x:Key="MessagePollCorrectBrush" Color="{ThemeResource MessagePollCorrectColor}"/>
```

2020-11-14 09:02 UTC, FrayxRulez commented on Unigram/Unigram/Themes/ThemeGreen.xaml
> +            <Color x:Key="MessagePollRightColor">#5DC452</Color>
You're declaring `MessagePollCorrectColor` and using `MessagePollRightColor` after.

```suggestion
            <Color x:Key="MessagePollCorrectColor">#5DC452</Color>
```

2020-11-17 16:27 UTC, MarcAnt01 commented
The first part is ready now

2020-11-17 21:18 UTC, FrayxRulez requested changes

2020-11-17 21:18 UTC, FrayxRulez commented on Unigram/Unigram/Controls/Messages/Content/PollContent.xaml.cs
> +                if (diff <= 5)
As said: this isn't enough, original visual state should be set if diff > 5. 
It would be also nice to programmatically check whether the state isn't set already, as right now you're setting it for each tick where the condition is met.

2020-11-17 21:18 UTC, FrayxRulez commented on Unigram/Unigram/Controls/Messages/Content/PollContent.xaml.cs
> +                    VisualState.GoToState(LayoutRoot, "isRunningOut", false);
"isRunningOut" doesn't respect project naming convention. A correct name could be "TimingOut", or simply "Timeout".

2020-11-18 11:29 UTC, MarcAnt01 commented on Unigram/Unigram/Controls/Messages/Content/PollContent.xaml.cs
> +                if (diff <= 5)
Set the the original VisualState, before checking if it is applied, I think it's better to complete the xaml file

2020-11-29 15:23 UTC, FrayxRulez approved these changes

2020-11-29 15:29 UTC, merged