Accessibility fixes
UnigramDev/Unigram pull request #2677
Opened 2022-03-14 19:00 UTC by beqabeqa473

This pullrequest makes possible to easily identify forwarded messages in messages list.
Also it adds full accessibility support and keyboard controll to the seekbar slider

2022-03-14 19:18 UTC, FrayxRulez requested changes

2022-03-14 19:18 UTC, FrayxRulez commented on Unigram/Unigram/Controls/PlaybackHeader.xaml.cs
> +            Slider.AddHandler(PreviewKeyDownEvent, new KeyEventHandler(Slider_KeyDown), true);
You sure that's necessary to hook PreviewKeyDown capturing handled events as well?
Maybe hooking `KeyDown` from the XAML is enough in this case.

2022-03-14 19:18 UTC, FrayxRulez commented on Unigram/Unigram/Controls/PlaybackSlider.cs
> +        }
This can be improved!
First of all there's no need to cast `double` to `int`, you can use `double` directly.
Second, I feel that it might be better to use standard `TimeSpan.ToString` overload, as in the code suggestion.

Here I'm not actually sure whether screen readers are able to read `00:05` in a decent way, tho.
If it's not the case, you can use `Locale.Declension` method to pluralize hours, minutes, and seconds (no need to include days here :)) respecting current language rules.

```suggestion
        private static string ReadableTime(double seconds)
        {
            var duration = TimeSpan.FromSeconds(seconds);
            if (duration.TotalHours >= 1)
            {
                return duration.ToString("h\\:mm\\:ss");
            }
            else
            {
                return duration.ToString("mm\\:ss");
            }
        }
```

2022-03-14 19:18 UTC, FrayxRulez commented on Unigram/Unigram/Views/ChatView.xaml.cs
> +            if ((args.VirtualKey == Windows.System.VirtualKey.Down || args.VirtualKey == Windows.System.VirtualKey.PageDown || args.VirtualKey == Windows.System.VirtualKey.PageUp) && FocusManager.Get
I'd recommend you to check the cases on line [#999](https://github.com/UnigramDev/Unigram/blob/d8835c7a32fecc0235bfec15ade2f91474b48b6d/Unigram/Unigram/Views/ChatView.xaml.cs#999) and [#1042](https://github.com/UnigramDev/Unigram/blob/d8835c7a32fecc0235bfec15ade2f91474b48b6d/Unigram/Unigram/Views/ChatView.xaml.cs), this is where `Up/PageUp` and `Down/PageDown` are handled and there's a call to `FocusManager.GetFocusedElement` already. I'd add `PlaybackSlider` there.

2022-03-14 19:50 UTC, beqabeqa473 commented on Unigram/Unigram/Views/ChatView.xaml.cs
> +            if ((args.VirtualKey == Windows.System.VirtualKey.Down || args.VirtualKey == Windows.System.VirtualKey.PageDown || args.VirtualKey == Windows.System.VirtualKey.PageUp) && FocusManager.Get
I intentionally did that to not repeat the same in other places.

2022-03-14 19:59 UTC, beqabeqa473 reviewed
I think most of suggestions were applied.

2022-03-15 09:49 UTC, beqabeqa473 commented
As for ChatView.xaml.cs, initialy i wanted to do aas you suggest, but
                var focused = FocusManager.GetFocusedElement();
is bellow line #999

2022-03-15 09:53 UTC, FrayxRulez commented
Adding the check in the if on line 1008 and 1046 would be perfect to do what you need to do, as you can see there are other cases already where we want to ignore those keys for specific controls. I'd recommend doing it there (still this method probably requires a lot of refactoring in general, but I'd like to keep it as it is until then).

Additionally, I'd recommend setting `AutomationProperties.AccessibilityView` in the XAML part instead of code behind. Thanks :)

2022-03-15 10:11 UTC, beqabeqa473 commented
> Adding the check in the if on line 1008 and 1046 would be perfect to do what you need to do, as you can see there are other cases already where we want to ignore those keys for specific controls. I'd recommend doing it there (still this method probably requires a lot of refactoring in general, but I'd like to keep it as it is until then).
> 
> Additionally, I'd recommend setting `AutomationProperties.AccessibilityView` in the XAML part instead of code behind. Thanks :)

I am sorry, i still don't get thing about key handling.

2022-03-15 10:40 UTC, beqabeqa473 commented
Done.

2022-03-15 13:24 UTC, FrayxRulez approved these changes

2022-03-15 13:24 UTC, merged