Add Spoiler shortcut
UnigramDev/Unigram pull request #2835
Opened 2022-09-18 06:52 UTC by makisukurisu

Do we really need classes for tr?

2022-10-10 09:20 UTC, FrayxRulez requested changes
Can you also add change status shortcut? It's `Ctrl+Shift+Y`

2022-10-10 09:20 UTC, FrayxRulez commented on Documentation/Shortcuts.md
> +            <td class="column2 style1 s">Ctrol + Shift + P</td>
Typo:
```suggestion
            <td class="column2 style1 s">Ctrl + Shift + P</td>
```

2022-10-11 15:33 UTC, FrayxRulez approved these changes
Is it actually really needed to assign a different class (that I guess doesn't even exist) to each row?

2022-10-11 15:36 UTC, makisukurisu commented
Classes are not necessary at all :sweat_smile: , wonder why they were there in the first place.

2022-10-12 08:02 UTC, FrayxRulez commented
> Classes are not necessary at all 😅 , wonder why they were there in the first place.

So maybe you could remove them

2022-10-12 16:49 UTC, makisukurisu commented
Done. I see no problems, but I'd like to ask someone to try to read this table with NVDA/Narrator just to make sure it's still accessible (because who knows - perhaps those classes were there for a reason).

Direct link to updated file:
https://github.com/UnigramDev/Unigram/blob/ab7d4c7323063c865a3369aced9ae6dba14989e7/Documentation/Shortcuts.md

2022-10-13 06:55 UTC, rehakp commented
@makisukurisu Thanks for the update. Well, basically the table is accessible but it could be better by just rendering column headings by using HTML <th></th> elements instead of <td></td>. This way screen readers will be able to recognize them as such and announce them accordingly if configured by a user.

2022-11-13 11:11 UTC, makisukurisu commented
@FrayxRulez , can you merge this?

2022-11-13 11:11 UTC, FrayxRulez commented
@makisukurisu You can, it’s your pull request

2022-11-13 11:12 UTC, MarcAnt01 approved these changes

2022-11-19 15:35 UTC, merged